input-field {
	monitor =
	size = 20%, 5%
}

label {
	monitor = 
	text = $TIME
	position = 0, -80
}

background {
	monitor = 
	path = ~/Pictures/wallpapers/artemis.jpg
	blur_passes = 1
	blur_size = 7
}
